language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_install: 
  - cd code
  - sudo brew install yarn

before_script:
  - npm install -g @angular/cli

script:
  - ng build

notifications:
  email:
    on_failure: change
    on_success: change
